name: Push-to-Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to EC2 on dev branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_DEV }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_KEY_DEV }}" ubuntu@${{ secrets.HOST_DNS_DEV }} << 'EOF'
            sudo apt update
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt update
            sudo apt install -y php8.2 php8.2-cli php8.2-fpm php8.2-mysql php8.2-xml php8.2-mbstring php8.2-curl php8.2-zip
            sudo update-alternatives --set php /usr/bin/php8.2
            sudo update-alternatives --set php-fpm /usr/sbin/php-fpm8.2
            php -v
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_rsa
            git config --global --add safe.directory /var/www/kasir-api
            cd /var/www/kasir-api
            git pull origin dev
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            sudo chown -R www-data:www-data storage
            sudo chmod -R 775 storage
            sudo chown -R www-data:www-data storage/logs
            sudo chmod -R 775 storage/logs
            sudo systemctl restart nginx
          EOF
