name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master # Ganti dengan nama branch yang ingin di-deploy

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          scp -r * ${REMOTE_USER}@${HOST_DNS}:${REMOTE_PATH}
          ssh ${REMOTE_USER}@${HOST_DNS} 'bash -s' < deploy.sh
        env:
          HOST_DNS: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PATH: /var/www/kasir-api
