name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.USERNAME }}
          port: 80
          key: ${{ secrets.EC2_SSH_KEY }}
          script: "cd /var/www/kasir-api && ./.scripts/deploy.sh"
