name: Deploy Laravel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci
          npm run build

      - name: Deploy to EC2
        env:
          HOST_DSN: ${{ secrets.HOST_DNS }}
          USER_NAME: ${{ secrets.USERNAME }}
          USER_PASSWORD: ${{ secrets.EC2_SSH_KEY }}
        run: |
          scp -r -o StrictHostKeyChecking=no ./public ./vendor ./storage ./artisan ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/kasir-api
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} "
            cd /var/www/kasir-api &&
            sudo chown -R www-data:www-data . &&
            sudo chmod -R 755 storage &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache
          "
