name: Deploy to Production

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/kasir-api

            # Pull latest changes
            echo "Pulling latest changes..."
            git pull origin production || exit 1

            # Install dependencies
            echo "Installing dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader || exit 1

            # Clear and cache configurations
            echo "Caching configurations..."
            php artisan config:clear || exit 1
            php artisan cache:clear || exit 1
            php artisan config:cache || exit 1
            php artisan route:cache || exit 1
            php artisan view:cache || exit 1

            # Run migrations
            echo "Running migrations..."
            php artisan migrate --force || exit 1

            # Fix permissions
            echo "Setting permissions..."
            sudo chown -R www-data:www-data .
            sudo find . -type f -exec chmod 644 {} \;
            sudo find . -type d -exec chmod 755 {} \;
            sudo chmod -R 775 storage bootstrap/cache

            # Restart Apache
            echo "Restarting Apache..."
            sudo systemctl restart apache2 || exit 1

            echo "Deployment completed successfully!"
