name: Deploy to DigitaOcean

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        env:
          COMPOSER_ALLOW_SUPERUSER: 1
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCEAN_HOST }}
          username: ${{ secrets.OCEAN_USERNAME }}
          key: ${{ secrets.OCEAN_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.OCEAN_PROJECT_PATH }}
            git fetch origin
            git checkout -f production
            git pull origin production
            composer install --no-dev --prefer-dist --no-interaction
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart apache2
